export const keyCodes = {
  arrowUp: 'ArrowUp',
  arrowDown: 'ArrowDown',
  arrowLeft: 'ArrowLeft',
  arrowRight: 'ArrowRight',
  backspace: 'Backspace',
  delete: 'Delete',
  space: 'Space',
  keyA: 'KeyA',
  keyD: 'KeyD',
  keyE: 'KeyE',
  keyF: 'KeyF',
  keyG: 'KeyG',
  keyH: 'KeyH',
  keyJ: 'KeyJ',
  keyS: 'KeyS',
  keyT: 'KeyT',
  keyU: 'KeyU',
  keyW: 'KeyW',
  keyY: 'KeyY',
} as const;
